### ISSUE TITLE
hass log error on startup - AttributeError: 'str' object has no attribute 'get_filename'

### ISSUE THREAD

**Issue by danpowpow** [emcniece/ha_imap_attachment#6]
Hi,
I'm hoping to set this component up to scrape cctv images sent to email by a camera with no local integration. Unfortunately I get this error in the home assistant logs.
Can you offer any insight?
cheers.

2022-06-12 15:50:45 ERROR (MainThread) [homeassistant.components.sensor] imap_attachment: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/ha_imap_attachment/sensor.py", line 301, in update
    ATTR_ATTACHMENT_PATHS: EmailContentSensor.get_msg_attachments(email_message, self._storage_path),
  File "/home/homeassistant/.homeassistant/custom_components/ha_imap_attachment/sensor.py", line 271, in get_msg_attachments
    filename = attachment.get_filename()
AttributeError: 'str' object has no attribute 'get_filename'

**Comment by emcniece** [comment]
Looks like the attachment is expected to be a file when it's a string. How many attachments are on these emails, and what kind of data are they?

**Comment by emcniece** [comment]
I've pushed https://github.com/emcniece/ha_imap_attachment/pull/7, give that a shot.

I'm not convinced this will fix the issue though - through some manual testing it appears that even `text` type attachments have accessors like `get_filename()` on them, and that error says that `attachment` is a string when it should be an object.

If this doesn't work maybe we can analyze `get_payload()` instead.

I've added some logging to that area as well, if the error happens again we should see HA logs.

**Comment by alexz707** [comment]
hi! I had the same problem but changing to your branch did not fix it.
There were other errors like variable part not defined...

I have now fixed it (for my needs only...) so maybe it helps you too:
This part of the code only grabs the csv attachments...
maybe you want to include a filter for specific attachments?



```python
attachments = []
        try:
            if email_message.is_multipart():
                for part in email_message.walk():
                    ctype = part.get_content_type()
                    cdispo = str(part.get('Content-Disposition'))
                    if 'attachment' not in cdispo:
                        continue
                    if ctype == 'text/csv' or ctype == 'text/comma-separated-values':
                        filename = part.get_filename()
                        fullpath = os.path.join(storage_path, filename)
                        open(fullpath, 'wb').write(part.get_payload(decode=True))
                        attachments.append(fullpath)
                        continue
            else:
                _LOGGER.error("Not multipart")
                fullpath = os.path.join(storage_path, filename)
                open(fullpath, 'wb').write(attachment.get_payload(decode=True))
                attachments.append(fullpath)
        except Exception as e:
                _LOGGER.error(f"Unexpected imap attachment: {email_message}")
                raise e

        return attachments
```

Regards 
Alex
